package com.jz;

import com.jz.IecsOperateInstrTrucks;
import java.util.List;

public interface IecsOperateInstrTrucksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IECS_OPERATE_INSTR_TRUCKS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long oisOpinstridId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IECS_OPERATE_INSTR_TRUCKS
     *
     * @mbggenerated
     */
    int insert(IecsOperateInstrTrucks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IECS_OPERATE_INSTR_TRUCKS
     *
     * @mbggenerated
     */
    IecsOperateInstrTrucks selectByPrimaryKey(Long oisOpinstridId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IECS_OPERATE_INSTR_TRUCKS
     *
     * @mbggenerated
     */
    List<IecsOperateInstrTrucks> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IECS_OPERATE_INSTR_TRUCKS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IecsOperateInstrTrucks record);
}