package com.jz;

import java.util.Date;

public class IecsOperateInstrTrucks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID_ID
     *
     * @mbggenerated
     */
    private Long oisOpinstridId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_IYC_CNTRID
     *
     * @mbggenerated
     */
    private Long oisIycCntrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VPC_CNTRID
     *
     * @mbggenerated
     */
    private Long oisVpcCntrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPPRC
     *
     * @mbggenerated
     */
    private String oisOpprc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPMODE
     *
     * @mbggenerated
     */
    private String oisOpmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PRIORITY
     *
     * @mbggenerated
     */
    private Short oisPriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_GENTM
     *
     * @mbggenerated
     */
    private Date oisGentm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPSTATUS
     *
     * @mbggenerated
     */
    private String oisOpstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_YLOCATION
     *
     * @mbggenerated
     */
    private String oisYlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VLOCATION
     *
     * @mbggenerated
     */
    private String oisVlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASKFINISHTIME
     *
     * @mbggenerated
     */
    private Date oisAskfinishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_FFNSHTIME
     *
     * @mbggenerated
     */
    private Date oisFfnshtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_REFRESHTIME
     *
     * @mbggenerated
     */
    private Date oisRefreshtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_WK_FLOW
     *
     * @mbggenerated
     */
    private String oisWkFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_FROMLOC
     *
     * @mbggenerated
     */
    private String oisFromloc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CURLOC
     *
     * @mbggenerated
     */
    private String oisCurloc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TOLOC
     *
     * @mbggenerated
     */
    private String oisToloc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CWP_ID
     *
     * @mbggenerated
     */
    private Long oisCwpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date oisTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ADDUSER
     *
     * @mbggenerated
     */
    private String oisAdduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_DELUSER
     *
     * @mbggenerated
     */
    private String oisDeluser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTDT
     *
     * @mbggenerated
     */
    private Date oisInsertdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTUSER
     *
     * @mbggenerated
     */
    private String oisInsertuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPDDT
     *
     * @mbggenerated
     */
    private Date oisLstupddt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPUSER
     *
     * @mbggenerated
     */
    private String oisLstupuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LANETIME
     *
     * @mbggenerated
     */
    private Date oisLanetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PSPLID
     *
     * @mbggenerated
     */
    private Long oisPsplid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASPLID
     *
     * @mbggenerated
     */
    private Long oisAsplid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VBT_ID
     *
     * @mbggenerated
     */
    private Long oisVbtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TRKNO
     *
     * @mbggenerated
     */
    private String oisTrkno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASKSTARTTIME
     *
     * @mbggenerated
     */
    private Date oisAskstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_WORKING_MODE
     *
     * @mbggenerated
     */
    private String oisWorkingMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TIME_LIMIT
     *
     * @mbggenerated
     */
    private Date oisTimeLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_NO
     *
     * @mbggenerated
     */
    private String oisCntrNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CCS_LOCATION
     *
     * @mbggenerated
     */
    private String oisCcsLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LOAD_LAST_TIME
     *
     * @mbggenerated
     */
    private Date oisLoadLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_UNLOAD_LAST_TIME
     *
     * @mbggenerated
     */
    private Date oisUnloadLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_START_TIME
     *
     * @mbggenerated
     */
    private Date oisTaskLastStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_END_TIME
     *
     * @mbggenerated
     */
    private Date oisTaskLastEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_AREA_LANE
     *
     * @mbggenerated
     */
    private String oisCntrAreaLane;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID
     *
     * @mbggenerated
     */
    private Long oisOpinstrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTR_SEQ
     *
     * @mbggenerated
     */
    private Long oisOpinstrSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_SEND_STATE
     *
     * @mbggenerated
     */
    private String oisSendState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_SHIP_NO
     *
     * @mbggenerated
     */
    private String oisShipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SPACE
     *
     * @mbggenerated
     */
    private String oisContainerSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_WEIGHT
     *
     * @mbggenerated
     */
    private Long oisContainerWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SIZE
     *
     * @mbggenerated
     */
    private String oisContainerSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_TYPE
     *
     * @mbggenerated
     */
    private String oisContainerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_FORM
     *
     * @mbggenerated
     */
    private String oisContainerForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_END_NODE_ID
     *
     * @mbggenerated
     */
    private Short oisEndNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ROAD_INFO
     *
     * @mbggenerated
     */
    private String oisRoadInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_JW_ROAD
     *
     * @mbggenerated
     */
    private String oisJwRoad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.RTG_LOCATION_INFO
     *
     * @mbggenerated
     */
    private String rtgLocationInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.CNTR_PLACE_STATE
     *
     * @mbggenerated
     */
    private String cntrPlaceState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.CNTR_LOAD_STATE
     *
     * @mbggenerated
     */
    private String cntrLoadState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_TYPE
     *
     * @mbggenerated
     */
    private String oisTaskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_DEPARTURE_TIME
     *
     * @mbggenerated
     */
    private Date oisDepartureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PASS_POINTS
     *
     * @mbggenerated
     */
    private String oisPassPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VCW_ID
     *
     * @mbggenerated
     */
    private Long oisVcwId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_REL_ID
     *
     * @mbggenerated
     */
    private Long oisRelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TWO_TASK_ID
     *
     * @mbggenerated
     */
    private Long oisTwoTaskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID_ID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID_ID
     *
     * @mbggenerated
     */
    public Long getOisOpinstridId() {
        return oisOpinstridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID_ID
     *
     * @param oisOpinstridId the value for IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID_ID
     *
     * @mbggenerated
     */
    public void setOisOpinstridId(Long oisOpinstridId) {
        this.oisOpinstridId = oisOpinstridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_IYC_CNTRID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_IYC_CNTRID
     *
     * @mbggenerated
     */
    public Long getOisIycCntrid() {
        return oisIycCntrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_IYC_CNTRID
     *
     * @param oisIycCntrid the value for IECS_OPERATE_INSTR_TRUCKS.OIS_IYC_CNTRID
     *
     * @mbggenerated
     */
    public void setOisIycCntrid(Long oisIycCntrid) {
        this.oisIycCntrid = oisIycCntrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VPC_CNTRID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_VPC_CNTRID
     *
     * @mbggenerated
     */
    public Long getOisVpcCntrid() {
        return oisVpcCntrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VPC_CNTRID
     *
     * @param oisVpcCntrid the value for IECS_OPERATE_INSTR_TRUCKS.OIS_VPC_CNTRID
     *
     * @mbggenerated
     */
    public void setOisVpcCntrid(Long oisVpcCntrid) {
        this.oisVpcCntrid = oisVpcCntrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPPRC
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_OPPRC
     *
     * @mbggenerated
     */
    public String getOisOpprc() {
        return oisOpprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPPRC
     *
     * @param oisOpprc the value for IECS_OPERATE_INSTR_TRUCKS.OIS_OPPRC
     *
     * @mbggenerated
     */
    public void setOisOpprc(String oisOpprc) {
        this.oisOpprc = oisOpprc == null ? null : oisOpprc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPMODE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_OPMODE
     *
     * @mbggenerated
     */
    public String getOisOpmode() {
        return oisOpmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPMODE
     *
     * @param oisOpmode the value for IECS_OPERATE_INSTR_TRUCKS.OIS_OPMODE
     *
     * @mbggenerated
     */
    public void setOisOpmode(String oisOpmode) {
        this.oisOpmode = oisOpmode == null ? null : oisOpmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PRIORITY
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_PRIORITY
     *
     * @mbggenerated
     */
    public Short getOisPriority() {
        return oisPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PRIORITY
     *
     * @param oisPriority the value for IECS_OPERATE_INSTR_TRUCKS.OIS_PRIORITY
     *
     * @mbggenerated
     */
    public void setOisPriority(Short oisPriority) {
        this.oisPriority = oisPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_GENTM
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_GENTM
     *
     * @mbggenerated
     */
    public Date getOisGentm() {
        return oisGentm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_GENTM
     *
     * @param oisGentm the value for IECS_OPERATE_INSTR_TRUCKS.OIS_GENTM
     *
     * @mbggenerated
     */
    public void setOisGentm(Date oisGentm) {
        this.oisGentm = oisGentm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPSTATUS
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_OPSTATUS
     *
     * @mbggenerated
     */
    public String getOisOpstatus() {
        return oisOpstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPSTATUS
     *
     * @param oisOpstatus the value for IECS_OPERATE_INSTR_TRUCKS.OIS_OPSTATUS
     *
     * @mbggenerated
     */
    public void setOisOpstatus(String oisOpstatus) {
        this.oisOpstatus = oisOpstatus == null ? null : oisOpstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_YLOCATION
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_YLOCATION
     *
     * @mbggenerated
     */
    public String getOisYlocation() {
        return oisYlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_YLOCATION
     *
     * @param oisYlocation the value for IECS_OPERATE_INSTR_TRUCKS.OIS_YLOCATION
     *
     * @mbggenerated
     */
    public void setOisYlocation(String oisYlocation) {
        this.oisYlocation = oisYlocation == null ? null : oisYlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VLOCATION
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_VLOCATION
     *
     * @mbggenerated
     */
    public String getOisVlocation() {
        return oisVlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VLOCATION
     *
     * @param oisVlocation the value for IECS_OPERATE_INSTR_TRUCKS.OIS_VLOCATION
     *
     * @mbggenerated
     */
    public void setOisVlocation(String oisVlocation) {
        this.oisVlocation = oisVlocation == null ? null : oisVlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASKFINISHTIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_ASKFINISHTIME
     *
     * @mbggenerated
     */
    public Date getOisAskfinishtime() {
        return oisAskfinishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASKFINISHTIME
     *
     * @param oisAskfinishtime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_ASKFINISHTIME
     *
     * @mbggenerated
     */
    public void setOisAskfinishtime(Date oisAskfinishtime) {
        this.oisAskfinishtime = oisAskfinishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_FFNSHTIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_FFNSHTIME
     *
     * @mbggenerated
     */
    public Date getOisFfnshtime() {
        return oisFfnshtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_FFNSHTIME
     *
     * @param oisFfnshtime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_FFNSHTIME
     *
     * @mbggenerated
     */
    public void setOisFfnshtime(Date oisFfnshtime) {
        this.oisFfnshtime = oisFfnshtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_REFRESHTIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_REFRESHTIME
     *
     * @mbggenerated
     */
    public Date getOisRefreshtime() {
        return oisRefreshtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_REFRESHTIME
     *
     * @param oisRefreshtime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_REFRESHTIME
     *
     * @mbggenerated
     */
    public void setOisRefreshtime(Date oisRefreshtime) {
        this.oisRefreshtime = oisRefreshtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_WK_FLOW
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_WK_FLOW
     *
     * @mbggenerated
     */
    public String getOisWkFlow() {
        return oisWkFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_WK_FLOW
     *
     * @param oisWkFlow the value for IECS_OPERATE_INSTR_TRUCKS.OIS_WK_FLOW
     *
     * @mbggenerated
     */
    public void setOisWkFlow(String oisWkFlow) {
        this.oisWkFlow = oisWkFlow == null ? null : oisWkFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_FROMLOC
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_FROMLOC
     *
     * @mbggenerated
     */
    public String getOisFromloc() {
        return oisFromloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_FROMLOC
     *
     * @param oisFromloc the value for IECS_OPERATE_INSTR_TRUCKS.OIS_FROMLOC
     *
     * @mbggenerated
     */
    public void setOisFromloc(String oisFromloc) {
        this.oisFromloc = oisFromloc == null ? null : oisFromloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CURLOC
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CURLOC
     *
     * @mbggenerated
     */
    public String getOisCurloc() {
        return oisCurloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CURLOC
     *
     * @param oisCurloc the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CURLOC
     *
     * @mbggenerated
     */
    public void setOisCurloc(String oisCurloc) {
        this.oisCurloc = oisCurloc == null ? null : oisCurloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TOLOC
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_TOLOC
     *
     * @mbggenerated
     */
    public String getOisToloc() {
        return oisToloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TOLOC
     *
     * @param oisToloc the value for IECS_OPERATE_INSTR_TRUCKS.OIS_TOLOC
     *
     * @mbggenerated
     */
    public void setOisToloc(String oisToloc) {
        this.oisToloc = oisToloc == null ? null : oisToloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CWP_ID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CWP_ID
     *
     * @mbggenerated
     */
    public Long getOisCwpId() {
        return oisCwpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CWP_ID
     *
     * @param oisCwpId the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CWP_ID
     *
     * @mbggenerated
     */
    public void setOisCwpId(Long oisCwpId) {
        this.oisCwpId = oisCwpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TIMESTAMP
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getOisTimestamp() {
        return oisTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TIMESTAMP
     *
     * @param oisTimestamp the value for IECS_OPERATE_INSTR_TRUCKS.OIS_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setOisTimestamp(Date oisTimestamp) {
        this.oisTimestamp = oisTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ADDUSER
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_ADDUSER
     *
     * @mbggenerated
     */
    public String getOisAdduser() {
        return oisAdduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ADDUSER
     *
     * @param oisAdduser the value for IECS_OPERATE_INSTR_TRUCKS.OIS_ADDUSER
     *
     * @mbggenerated
     */
    public void setOisAdduser(String oisAdduser) {
        this.oisAdduser = oisAdduser == null ? null : oisAdduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_DELUSER
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_DELUSER
     *
     * @mbggenerated
     */
    public String getOisDeluser() {
        return oisDeluser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_DELUSER
     *
     * @param oisDeluser the value for IECS_OPERATE_INSTR_TRUCKS.OIS_DELUSER
     *
     * @mbggenerated
     */
    public void setOisDeluser(String oisDeluser) {
        this.oisDeluser = oisDeluser == null ? null : oisDeluser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTDT
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTDT
     *
     * @mbggenerated
     */
    public Date getOisInsertdt() {
        return oisInsertdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTDT
     *
     * @param oisInsertdt the value for IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTDT
     *
     * @mbggenerated
     */
    public void setOisInsertdt(Date oisInsertdt) {
        this.oisInsertdt = oisInsertdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTUSER
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTUSER
     *
     * @mbggenerated
     */
    public String getOisInsertuser() {
        return oisInsertuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTUSER
     *
     * @param oisInsertuser the value for IECS_OPERATE_INSTR_TRUCKS.OIS_INSERTUSER
     *
     * @mbggenerated
     */
    public void setOisInsertuser(String oisInsertuser) {
        this.oisInsertuser = oisInsertuser == null ? null : oisInsertuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPDDT
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPDDT
     *
     * @mbggenerated
     */
    public Date getOisLstupddt() {
        return oisLstupddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPDDT
     *
     * @param oisLstupddt the value for IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPDDT
     *
     * @mbggenerated
     */
    public void setOisLstupddt(Date oisLstupddt) {
        this.oisLstupddt = oisLstupddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPUSER
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPUSER
     *
     * @mbggenerated
     */
    public String getOisLstupuser() {
        return oisLstupuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPUSER
     *
     * @param oisLstupuser the value for IECS_OPERATE_INSTR_TRUCKS.OIS_LSTUPUSER
     *
     * @mbggenerated
     */
    public void setOisLstupuser(String oisLstupuser) {
        this.oisLstupuser = oisLstupuser == null ? null : oisLstupuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LANETIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_LANETIME
     *
     * @mbggenerated
     */
    public Date getOisLanetime() {
        return oisLanetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LANETIME
     *
     * @param oisLanetime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_LANETIME
     *
     * @mbggenerated
     */
    public void setOisLanetime(Date oisLanetime) {
        this.oisLanetime = oisLanetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PSPLID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_PSPLID
     *
     * @mbggenerated
     */
    public Long getOisPsplid() {
        return oisPsplid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PSPLID
     *
     * @param oisPsplid the value for IECS_OPERATE_INSTR_TRUCKS.OIS_PSPLID
     *
     * @mbggenerated
     */
    public void setOisPsplid(Long oisPsplid) {
        this.oisPsplid = oisPsplid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASPLID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_ASPLID
     *
     * @mbggenerated
     */
    public Long getOisAsplid() {
        return oisAsplid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASPLID
     *
     * @param oisAsplid the value for IECS_OPERATE_INSTR_TRUCKS.OIS_ASPLID
     *
     * @mbggenerated
     */
    public void setOisAsplid(Long oisAsplid) {
        this.oisAsplid = oisAsplid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VBT_ID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_VBT_ID
     *
     * @mbggenerated
     */
    public Long getOisVbtId() {
        return oisVbtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VBT_ID
     *
     * @param oisVbtId the value for IECS_OPERATE_INSTR_TRUCKS.OIS_VBT_ID
     *
     * @mbggenerated
     */
    public void setOisVbtId(Long oisVbtId) {
        this.oisVbtId = oisVbtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TRKNO
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_TRKNO
     *
     * @mbggenerated
     */
    public String getOisTrkno() {
        return oisTrkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TRKNO
     *
     * @param oisTrkno the value for IECS_OPERATE_INSTR_TRUCKS.OIS_TRKNO
     *
     * @mbggenerated
     */
    public void setOisTrkno(String oisTrkno) {
        this.oisTrkno = oisTrkno == null ? null : oisTrkno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASKSTARTTIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_ASKSTARTTIME
     *
     * @mbggenerated
     */
    public Date getOisAskstarttime() {
        return oisAskstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ASKSTARTTIME
     *
     * @param oisAskstarttime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_ASKSTARTTIME
     *
     * @mbggenerated
     */
    public void setOisAskstarttime(Date oisAskstarttime) {
        this.oisAskstarttime = oisAskstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_WORKING_MODE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_WORKING_MODE
     *
     * @mbggenerated
     */
    public String getOisWorkingMode() {
        return oisWorkingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_WORKING_MODE
     *
     * @param oisWorkingMode the value for IECS_OPERATE_INSTR_TRUCKS.OIS_WORKING_MODE
     *
     * @mbggenerated
     */
    public void setOisWorkingMode(String oisWorkingMode) {
        this.oisWorkingMode = oisWorkingMode == null ? null : oisWorkingMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TIME_LIMIT
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_TIME_LIMIT
     *
     * @mbggenerated
     */
    public Date getOisTimeLimit() {
        return oisTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TIME_LIMIT
     *
     * @param oisTimeLimit the value for IECS_OPERATE_INSTR_TRUCKS.OIS_TIME_LIMIT
     *
     * @mbggenerated
     */
    public void setOisTimeLimit(Date oisTimeLimit) {
        this.oisTimeLimit = oisTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_NO
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_NO
     *
     * @mbggenerated
     */
    public String getOisCntrNo() {
        return oisCntrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_NO
     *
     * @param oisCntrNo the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_NO
     *
     * @mbggenerated
     */
    public void setOisCntrNo(String oisCntrNo) {
        this.oisCntrNo = oisCntrNo == null ? null : oisCntrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CCS_LOCATION
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CCS_LOCATION
     *
     * @mbggenerated
     */
    public String getOisCcsLocation() {
        return oisCcsLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CCS_LOCATION
     *
     * @param oisCcsLocation the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CCS_LOCATION
     *
     * @mbggenerated
     */
    public void setOisCcsLocation(String oisCcsLocation) {
        this.oisCcsLocation = oisCcsLocation == null ? null : oisCcsLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LOAD_LAST_TIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_LOAD_LAST_TIME
     *
     * @mbggenerated
     */
    public Date getOisLoadLastTime() {
        return oisLoadLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_LOAD_LAST_TIME
     *
     * @param oisLoadLastTime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_LOAD_LAST_TIME
     *
     * @mbggenerated
     */
    public void setOisLoadLastTime(Date oisLoadLastTime) {
        this.oisLoadLastTime = oisLoadLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_UNLOAD_LAST_TIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_UNLOAD_LAST_TIME
     *
     * @mbggenerated
     */
    public Date getOisUnloadLastTime() {
        return oisUnloadLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_UNLOAD_LAST_TIME
     *
     * @param oisUnloadLastTime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_UNLOAD_LAST_TIME
     *
     * @mbggenerated
     */
    public void setOisUnloadLastTime(Date oisUnloadLastTime) {
        this.oisUnloadLastTime = oisUnloadLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_START_TIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_START_TIME
     *
     * @mbggenerated
     */
    public Date getOisTaskLastStartTime() {
        return oisTaskLastStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_START_TIME
     *
     * @param oisTaskLastStartTime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_START_TIME
     *
     * @mbggenerated
     */
    public void setOisTaskLastStartTime(Date oisTaskLastStartTime) {
        this.oisTaskLastStartTime = oisTaskLastStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_END_TIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_END_TIME
     *
     * @mbggenerated
     */
    public Date getOisTaskLastEndTime() {
        return oisTaskLastEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_END_TIME
     *
     * @param oisTaskLastEndTime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_LAST_END_TIME
     *
     * @mbggenerated
     */
    public void setOisTaskLastEndTime(Date oisTaskLastEndTime) {
        this.oisTaskLastEndTime = oisTaskLastEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_AREA_LANE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_AREA_LANE
     *
     * @mbggenerated
     */
    public String getOisCntrAreaLane() {
        return oisCntrAreaLane;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_AREA_LANE
     *
     * @param oisCntrAreaLane the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CNTR_AREA_LANE
     *
     * @mbggenerated
     */
    public void setOisCntrAreaLane(String oisCntrAreaLane) {
        this.oisCntrAreaLane = oisCntrAreaLane == null ? null : oisCntrAreaLane.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID
     *
     * @mbggenerated
     */
    public Long getOisOpinstrid() {
        return oisOpinstrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID
     *
     * @param oisOpinstrid the value for IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTRID
     *
     * @mbggenerated
     */
    public void setOisOpinstrid(Long oisOpinstrid) {
        this.oisOpinstrid = oisOpinstrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTR_SEQ
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTR_SEQ
     *
     * @mbggenerated
     */
    public Long getOisOpinstrSeq() {
        return oisOpinstrSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTR_SEQ
     *
     * @param oisOpinstrSeq the value for IECS_OPERATE_INSTR_TRUCKS.OIS_OPINSTR_SEQ
     *
     * @mbggenerated
     */
    public void setOisOpinstrSeq(Long oisOpinstrSeq) {
        this.oisOpinstrSeq = oisOpinstrSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_SEND_STATE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_SEND_STATE
     *
     * @mbggenerated
     */
    public String getOisSendState() {
        return oisSendState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_SEND_STATE
     *
     * @param oisSendState the value for IECS_OPERATE_INSTR_TRUCKS.OIS_SEND_STATE
     *
     * @mbggenerated
     */
    public void setOisSendState(String oisSendState) {
        this.oisSendState = oisSendState == null ? null : oisSendState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_SHIP_NO
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_SHIP_NO
     *
     * @mbggenerated
     */
    public String getOisShipNo() {
        return oisShipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_SHIP_NO
     *
     * @param oisShipNo the value for IECS_OPERATE_INSTR_TRUCKS.OIS_SHIP_NO
     *
     * @mbggenerated
     */
    public void setOisShipNo(String oisShipNo) {
        this.oisShipNo = oisShipNo == null ? null : oisShipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SPACE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SPACE
     *
     * @mbggenerated
     */
    public String getOisContainerSpace() {
        return oisContainerSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SPACE
     *
     * @param oisContainerSpace the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SPACE
     *
     * @mbggenerated
     */
    public void setOisContainerSpace(String oisContainerSpace) {
        this.oisContainerSpace = oisContainerSpace == null ? null : oisContainerSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_WEIGHT
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_WEIGHT
     *
     * @mbggenerated
     */
    public Long getOisContainerWeight() {
        return oisContainerWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_WEIGHT
     *
     * @param oisContainerWeight the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_WEIGHT
     *
     * @mbggenerated
     */
    public void setOisContainerWeight(Long oisContainerWeight) {
        this.oisContainerWeight = oisContainerWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SIZE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SIZE
     *
     * @mbggenerated
     */
    public String getOisContainerSize() {
        return oisContainerSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SIZE
     *
     * @param oisContainerSize the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_SIZE
     *
     * @mbggenerated
     */
    public void setOisContainerSize(String oisContainerSize) {
        this.oisContainerSize = oisContainerSize == null ? null : oisContainerSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_TYPE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_TYPE
     *
     * @mbggenerated
     */
    public String getOisContainerType() {
        return oisContainerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_TYPE
     *
     * @param oisContainerType the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_TYPE
     *
     * @mbggenerated
     */
    public void setOisContainerType(String oisContainerType) {
        this.oisContainerType = oisContainerType == null ? null : oisContainerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_FORM
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_FORM
     *
     * @mbggenerated
     */
    public String getOisContainerForm() {
        return oisContainerForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_FORM
     *
     * @param oisContainerForm the value for IECS_OPERATE_INSTR_TRUCKS.OIS_CONTAINER_FORM
     *
     * @mbggenerated
     */
    public void setOisContainerForm(String oisContainerForm) {
        this.oisContainerForm = oisContainerForm == null ? null : oisContainerForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_END_NODE_ID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_END_NODE_ID
     *
     * @mbggenerated
     */
    public Short getOisEndNodeId() {
        return oisEndNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_END_NODE_ID
     *
     * @param oisEndNodeId the value for IECS_OPERATE_INSTR_TRUCKS.OIS_END_NODE_ID
     *
     * @mbggenerated
     */
    public void setOisEndNodeId(Short oisEndNodeId) {
        this.oisEndNodeId = oisEndNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ROAD_INFO
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_ROAD_INFO
     *
     * @mbggenerated
     */
    public String getOisRoadInfo() {
        return oisRoadInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_ROAD_INFO
     *
     * @param oisRoadInfo the value for IECS_OPERATE_INSTR_TRUCKS.OIS_ROAD_INFO
     *
     * @mbggenerated
     */
    public void setOisRoadInfo(String oisRoadInfo) {
        this.oisRoadInfo = oisRoadInfo == null ? null : oisRoadInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_JW_ROAD
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_JW_ROAD
     *
     * @mbggenerated
     */
    public String getOisJwRoad() {
        return oisJwRoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_JW_ROAD
     *
     * @param oisJwRoad the value for IECS_OPERATE_INSTR_TRUCKS.OIS_JW_ROAD
     *
     * @mbggenerated
     */
    public void setOisJwRoad(String oisJwRoad) {
        this.oisJwRoad = oisJwRoad == null ? null : oisJwRoad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.RTG_LOCATION_INFO
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.RTG_LOCATION_INFO
     *
     * @mbggenerated
     */
    public String getRtgLocationInfo() {
        return rtgLocationInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.RTG_LOCATION_INFO
     *
     * @param rtgLocationInfo the value for IECS_OPERATE_INSTR_TRUCKS.RTG_LOCATION_INFO
     *
     * @mbggenerated
     */
    public void setRtgLocationInfo(String rtgLocationInfo) {
        this.rtgLocationInfo = rtgLocationInfo == null ? null : rtgLocationInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.CNTR_PLACE_STATE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.CNTR_PLACE_STATE
     *
     * @mbggenerated
     */
    public String getCntrPlaceState() {
        return cntrPlaceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.CNTR_PLACE_STATE
     *
     * @param cntrPlaceState the value for IECS_OPERATE_INSTR_TRUCKS.CNTR_PLACE_STATE
     *
     * @mbggenerated
     */
    public void setCntrPlaceState(String cntrPlaceState) {
        this.cntrPlaceState = cntrPlaceState == null ? null : cntrPlaceState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.CNTR_LOAD_STATE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.CNTR_LOAD_STATE
     *
     * @mbggenerated
     */
    public String getCntrLoadState() {
        return cntrLoadState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.CNTR_LOAD_STATE
     *
     * @param cntrLoadState the value for IECS_OPERATE_INSTR_TRUCKS.CNTR_LOAD_STATE
     *
     * @mbggenerated
     */
    public void setCntrLoadState(String cntrLoadState) {
        this.cntrLoadState = cntrLoadState == null ? null : cntrLoadState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_TYPE
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_TYPE
     *
     * @mbggenerated
     */
    public String getOisTaskType() {
        return oisTaskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_TYPE
     *
     * @param oisTaskType the value for IECS_OPERATE_INSTR_TRUCKS.OIS_TASK_TYPE
     *
     * @mbggenerated
     */
    public void setOisTaskType(String oisTaskType) {
        this.oisTaskType = oisTaskType == null ? null : oisTaskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_DEPARTURE_TIME
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_DEPARTURE_TIME
     *
     * @mbggenerated
     */
    public Date getOisDepartureTime() {
        return oisDepartureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_DEPARTURE_TIME
     *
     * @param oisDepartureTime the value for IECS_OPERATE_INSTR_TRUCKS.OIS_DEPARTURE_TIME
     *
     * @mbggenerated
     */
    public void setOisDepartureTime(Date oisDepartureTime) {
        this.oisDepartureTime = oisDepartureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PASS_POINTS
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_PASS_POINTS
     *
     * @mbggenerated
     */
    public String getOisPassPoints() {
        return oisPassPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_PASS_POINTS
     *
     * @param oisPassPoints the value for IECS_OPERATE_INSTR_TRUCKS.OIS_PASS_POINTS
     *
     * @mbggenerated
     */
    public void setOisPassPoints(String oisPassPoints) {
        this.oisPassPoints = oisPassPoints == null ? null : oisPassPoints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VCW_ID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_VCW_ID
     *
     * @mbggenerated
     */
    public Long getOisVcwId() {
        return oisVcwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_VCW_ID
     *
     * @param oisVcwId the value for IECS_OPERATE_INSTR_TRUCKS.OIS_VCW_ID
     *
     * @mbggenerated
     */
    public void setOisVcwId(Long oisVcwId) {
        this.oisVcwId = oisVcwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_REL_ID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_REL_ID
     *
     * @mbggenerated
     */
    public Long getOisRelId() {
        return oisRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_REL_ID
     *
     * @param oisRelId the value for IECS_OPERATE_INSTR_TRUCKS.OIS_REL_ID
     *
     * @mbggenerated
     */
    public void setOisRelId(Long oisRelId) {
        this.oisRelId = oisRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TWO_TASK_ID
     *
     * @return the value of IECS_OPERATE_INSTR_TRUCKS.OIS_TWO_TASK_ID
     *
     * @mbggenerated
     */
    public Long getOisTwoTaskId() {
        return oisTwoTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IECS_OPERATE_INSTR_TRUCKS.OIS_TWO_TASK_ID
     *
     * @param oisTwoTaskId the value for IECS_OPERATE_INSTR_TRUCKS.OIS_TWO_TASK_ID
     *
     * @mbggenerated
     */
    public void setOisTwoTaskId(Long oisTwoTaskId) {
        this.oisTwoTaskId = oisTwoTaskId;
    }
}